version: "3.1"
services:
  api:
    image: sqa-survey/api
    depends_on:
      - mysqldb
    ports:
      - 3001:3001
  mysqldb:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    env_file: ./api/.env
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sqa_survey_app
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
      - ./api/import_sqa_survey_db.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db-config:
  db-data:
